// Mocks generated by Mockito 5.3.2 from annotations
// in core/test/presentation/pages/tv_series/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:core/core.dart' as _i9;
import 'package:core/domain/entities/tv_series.dart' as _i10;
import 'package:core/domain/entities/tv_series_detail.dart' as _i7;
import 'package:core/domain/usecases/tv_series/get_recommendations_tv_series_usecase.dart'
    as _i3;
import 'package:core/domain/usecases/tv_series/get_tv_series_detail_usecase.dart'
    as _i2;
import 'package:core/domain/usecases/tv_series/get_tv_series_watchlist_status_usecase.dart'
    as _i4;
import 'package:core/domain/usecases/tv_series/remove_tv_series_watchlist_usecase.dart'
    as _i6;
import 'package:core/domain/usecases/tv_series/save_tv_series_watchlist_usecase.dart'
    as _i5;
import 'package:core/presentation/provider/tv_series/tv_series_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvSeriesDetailUseCase_0 extends _i1.SmartFake
    implements _i2.GetTvSeriesDetailUseCase {
  _FakeGetTvSeriesDetailUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRecommendationsTvSeriesUseCase_1 extends _i1.SmartFake
    implements _i3.GetRecommendationsTvSeriesUseCase {
  _FakeGetRecommendationsTvSeriesUseCase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesWatchListStatusUseCase_2 extends _i1.SmartFake
    implements _i4.GetTvSeriesWatchListStatusUseCase {
  _FakeGetTvSeriesWatchListStatusUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveTvSeriesWatchlistUseCase_3 extends _i1.SmartFake
    implements _i5.SaveTvSeriesWatchlistUseCase {
  _FakeSaveTvSeriesWatchlistUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveTvSeriesWatchlistUseCase_4 extends _i1.SmartFake
    implements _i6.RemoveTvSeriesWatchlistUseCase {
  _FakeRemoveTvSeriesWatchlistUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetail_5 extends _i1.SmartFake
    implements _i7.TvSeriesDetail {
  _FakeTvSeriesDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i8.TvSeriesDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvSeriesDetailUseCase get getTvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesDetail),
        returnValue: _FakeGetTvSeriesDetailUseCase_0(
          this,
          Invocation.getter(#getTvSeriesDetail),
        ),
      ) as _i2.GetTvSeriesDetailUseCase);
  @override
  _i3.GetRecommendationsTvSeriesUseCase get getTvSeriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendations),
        returnValue: _FakeGetRecommendationsTvSeriesUseCase_1(
          this,
          Invocation.getter(#getTvSeriesRecommendations),
        ),
      ) as _i3.GetRecommendationsTvSeriesUseCase);
  @override
  _i4.GetTvSeriesWatchListStatusUseCase get getWatchListStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetTvSeriesWatchListStatusUseCase_2(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i4.GetTvSeriesWatchListStatusUseCase);
  @override
  _i5.SaveTvSeriesWatchlistUseCase get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveTvSeriesWatchlistUseCase_3(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i5.SaveTvSeriesWatchlistUseCase);
  @override
  _i6.RemoveTvSeriesWatchlistUseCase get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveTvSeriesWatchlistUseCase_4(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i6.RemoveTvSeriesWatchlistUseCase);
  @override
  _i7.TvSeriesDetail get tvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#tvSeriesDetail),
        returnValue: _FakeTvSeriesDetail_5(
          this,
          Invocation.getter(#tvSeriesDetail),
        ),
      ) as _i7.TvSeriesDetail);
  @override
  _i9.RequestState get tvSeriesDetailState => (super.noSuchMethod(
        Invocation.getter(#tvSeriesDetailState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);
  @override
  List<_i10.TvSeries> get movieRecommendations => (super.noSuchMethod(
        Invocation.getter(#movieRecommendations),
        returnValue: <_i10.TvSeries>[],
      ) as List<_i10.TvSeries>);
  @override
  _i9.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> fetchMovieDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchMovieDetail,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tvSeries],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvSeries],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
