// Mocks generated by Mockito 5.3.2 from annotations
// in feature_tv/test/presentation/pages/search_tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:core/core.dart' as _i4;
import 'package:feature_tv/domain/entities/tv_series.dart' as _i5;
import 'package:feature_tv/domain/usecases/search_tv_series_usecase.dart'
    as _i2;
import 'package:feature_tv/presentation/provider/tv_series_search_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchTvSeriesUseCase_0 extends _i1.SmartFake
    implements _i2.SearchTvSeriesUseCase {
  _FakeSearchTvSeriesUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesSearchNotifier extends _i1.Mock
    implements _i3.TvSeriesSearchNotifier {
  MockTvSeriesSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchTvSeriesUseCase get searchTvSeriesUseCase => (super.noSuchMethod(
        Invocation.getter(#searchTvSeriesUseCase),
        returnValue: _FakeSearchTvSeriesUseCase_0(
          this,
          Invocation.getter(#searchTvSeriesUseCase),
        ),
      ) as _i2.SearchTvSeriesUseCase);
  @override
  _i4.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i4.RequestState.Empty,
      ) as _i4.RequestState);
  @override
  List<_i5.TvSeries> get searchResult => (super.noSuchMethod(
        Invocation.getter(#searchResult),
        returnValue: <_i5.TvSeries>[],
      ) as List<_i5.TvSeries>);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i6.Future<void> fetchTvSeriesSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvSeriesSearch,
          [query],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
